import type { Roster } from "@/lib/ambassador-panel/types";

/**
 * The roster as it stood in the original app's `src/ambassadors.ts` (and the
 * matching SLOTS/CORE/SUB tables in its `api/redirect.ts`). It seeds the Redis
 * roster the first time the panel reads it; after that, edits are saved to
 * Redis and this file is only a fallback when Redis is not configured.
 */
export const SEED_ROSTER: Roster = {
  educraft_whatsapp: "2347063421088",
  slots: {
    "001": { name: "Admins", school: "Admin", status: "active" },
    "002": { name: "Noruwosa Zoe", school: "UNIBEN", status: "active" },
    "003": { name: "Cassandra", school: "DELSU", status: "active" },
    "004": { name: "Marong", school: "EUI", status: "active" },
    "005": { name: "Chidinma", school: "EUI", status: "active" },
    "006": { name: "Debby", school: "EUI", status: "active" },
    "007": { name: "Osheho", school: "EUI", status: "active" },
    "008": { name: "Ayomidele", school: "UNIBEN", status: "active" },
    "009": { name: "Goodness", school: "EUI", status: "active" },
    "010": { name: "Ib Nation", school: "EUI", status: "active" },
    "011": { name: "Fortune", school: "EUI", status: "active" },
    "012": { name: "Obehi", school: "EUI", status: "active" },
    "013": { name: "Princewill", school: "EUI", status: "active" },
    "014": { name: "Sultan", school: "EUI", status: "active" },
    "015": { name: "Taiwo", school: "EUI", status: "active" },
    "016": { name: "Aisosa (MLS)", school: "EUI", status: "active" },
    "017": { name: "", school: "", status: "vacant" },
    "018": { name: "", school: "", status: "vacant" },
    "019": { name: "", school: "", status: "vacant" },
    "020": { name: "", school: "", status: "vacant" },
    "021": { name: "", school: "", status: "vacant" },
    "022": { name: "Blue Chief", school: "EUI", status: "active" },
    "023": { name: "Promzex", school: "EUI", status: "active" },
    "024": { name: "Confidence", school: "EUI", status: "active" },
    "025": { name: "Fredrick", school: "EUI", status: "active" },
    "026": { name: "Esosa", school: "PG", status: "active" },
    "027": { name: "David English", school: "EUI", status: "active" },
    "028": { name: "Chibuzor", school: "EUI", status: "active" },
    "029": { name: "Queen Precious", school: "EUI", status: "active" },
    "030": { name: "Cynthia", school: "EUI", status: "active" },
    "031": { name: "Miracle", school: "EUI", status: "active" },
    "032": { name: "Abdullahi", school: "EUI", status: "active" },
    "033": { name: "Gift", school: "EUI", status: "active" },
    "034": { name: "Doreen", school: "EUI", status: "active" },
    "035": { name: "David Salam", school: "EUI", status: "active" },
    "036": { name: "", school: "", status: "vacant" },
    "037": { name: "", school: "", status: "vacant" },
    "038": { name: "Victory Teshua", school: "EUI", status: "active" },
    "039": { name: "Collins", school: "EUI", status: "active" },
    "040": { name: "Favy", school: "EUI", status: "active" },
    "041": { name: "Deborah", school: "EUI", status: "active" },
    "042": { name: "Aisosa", school: "EUI", status: "active" },
    "043": { name: "Engine Boy", school: "UNIBEN", status: "active" },
    "044": { name: "Adenike", school: "UNIBEN", status: "active" },
    "045": { name: "Precious", school: "EUI", status: "active" },
    "046": { name: "Ayo (Bridget)", school: "EUI", status: "active" },
    "047": { name: "Raqeeb", school: "EUI", status: "active" },
    "048": { name: "Michael", school: "EUI", status: "active" },
    "049": { name: "", school: "", status: "vacant" },
    "050": { name: "Joshua (COE)", school: "EUI", status: "active" },
    "051": { name: "", school: "", status: "vacant" },
    "052": { name: "", school: "", status: "vacant" },
    "053": { name: "", school: "EUI", status: "vacant" },
    "054": { name: "", school: "EUI", status: "vacant" },
    "055": { name: "", school: "EUI", status: "vacant" },
    "056": { name: "", school: "EUI", status: "vacant" },
    "057": { name: "", school: "EUI", status: "vacant" },
    "058": { name: "", school: "EUI", status: "vacant" },
    "059": { name: "", school: "EUI", status: "vacant" },
    "060": { name: "", school: "EUI", status: "vacant" },
  },
  coreAmbassadors: [
    { id: "ECCA-001", name: "Chidinma Victory", school: "EUI", percentage: 10, status: "active" },
    { id: "ECCA-002", name: "Debby", school: "EUI", percentage: 10, status: "active" },
    { id: "ECCA-003", name: "Admins", school: "Admin", percentage: 10, status: "active" },
    { id: "ECCA-004", name: "Zoe Grace", school: "EUI", percentage: 10, status: "active" },
    { id: "ECCA-005", name: "Yole", school: "EUI", percentage: 10, status: "active" },
    { id: "ECCA-006", name: "Marong", school: "EUI", percentage: 10, status: "active" },
  ],
  subAmbassadors: [
    { id: "ECSA-001-001", name: "Rita", school: "Edwin Clark", percentage: 5, coreId: "ECCA-001", status: "active" },
    { id: "ECSA-001-002", name: "Praise", school: "SDU", percentage: 5, coreId: "ECCA-001", status: "active" },
    { id: "ECSA-001-003", name: "Queensly", school: "EUI", percentage: 5, coreId: "ECCA-001", status: "active" },
  ],
};

/** Full school names for the abbreviations used in the roster. */
export const SCHOOL_NAMES: Record<string, string> = {
  EUI: "Edo State University",
  UNIBEN: "University of Benin",
  DELSU: "Delta State University",
  AAU: "Ambrose Alli University",
  ECU: "Edwin Clark University",
  SDU: "University of Southern Denmark",
  UNILAG: "University of Lagos",
  PG: "Postgraduate Students",
  Admin: "Administration",
  UNICAL: "University of Calabar",
  OAU: "Obafemi Awolowo University",
  UI: "University of Ibadan",
  UNILORIN: "University of Ilorin",
  ABU: "Ahmadu Bello University",
  LASU: "Lagos State University",
  FUTA: "Federal University of Technology Akure",
  FUTO: "Federal University of Technology Owerri",
  COOU: "Chukwuemeka Odumegwu Ojukwu University",
  IMSU: "Imo State University",
  ESUT: "Enugu State University of Science and Technology",
  UNIZIK: "Nnamdi Azikiwe University",
  "Co-founders": "EduCraft Co-founders",
};
